"use client";
import { useEffect, useMemo, useState } from "react";
import { analyse, Business, demoBusiness, Service, Status } from "../../lib/model";

type Tab="home"|"services"|"coach"|"goals"|"team"|"more";
const money=new Intl.NumberFormat("en-NZ",{style:"currency",currency:"NZD",maximumFractionDigits:0});
const tabs:{id:Tab;label:string;icon:string}[]=[{id:"home",label:"Home",icon:"⌂"},{id:"services",label:"Services",icon:"✂"},{id:"coach",label:"Coach",icon:"✦"},{id:"goals",label:"Goals",icon:"◎"},{id:"team",label:"Team",icon:"♙"},{id:"more",label:"More",icon:"•••"}];

export default function Dashboard(){
 const [tab,setTab]=useState<Tab>("home"); const [business,setBusiness]=useState<Business>(demoBusiness); const [ready,setReady]=useState(false);
 useEffect(()=>{try{const saved=localStorage.getItem("barberbench-beta04");if(saved)setBusiness(JSON.parse(saved))}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("barberbench-beta04",JSON.stringify(business))},[business,ready]);
 const a=useMemo(()=>analyse(business),[business]);
 if(!ready)return <main className="loading">BarberBench IQ</main>;
 return <main className="shell"><aside className="rail"><div className="brand"><span className="mark">B</span><span>BarberBench <b>IQ</b></span></div><div className="profile"><div className="avatar">B</div><div><b>Founder account</b><span>Demo workspace</span></div></div><nav>{tabs.map(x=><button key={x.id} className={tab===x.id?"active":""} onClick={()=>setTab(x.id)}><i>{x.icon}</i>{x.label}</button>)}</nav><div className="railScore"><span>BUSINESS SCORE</span><b>{a.score}<small>/100</small></b><em className={tone(a.score,80,65)}>Live from your numbers</em></div></aside>
 <section className="main"><header><div className="mobileBrand"><span className="mark">B</span> BarberBench <b>IQ</b></div><div className="headerRight"><span className="liveDot"/> Founder Beta 0.4</div></header><div className="content">
 {tab==="home"&&<Home a={a} business={business} setTab={setTab}/>} {tab==="services"&&<Services business={business} setBusiness={setBusiness} a={a}/>} {tab==="coach"&&<Coach a={a}/>} {tab==="goals"&&<Goals business={business} setBusiness={setBusiness} a={a}/>} {tab==="team"&&<Team business={business}/>} {tab==="more"&&<More a={a}/>}</div>
 <nav className="bottomTabs">{tabs.map(x=><button key={x.id} className={tab===x.id?"active":""} onClick={()=>setTab(x.id)}><i>{x.icon}</i><span>{x.label}</span></button>)}</nav></section></main>
}
function tone(v:number,g:number,w:number):Status{return v>=g?"good":v>=w?"warn":"bad"}
function Heading({kicker,title,copy}:{kicker:string;title:string;copy?:string}){return <div className="heading"><span>{kicker}</span><h1>{title}</h1>{copy&&<p>{copy}</p>}</div>}
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
function Badge({status,children}:{status:Status;children:React.ReactNode}){return <span className={`badge ${status}`}>{children}</span>}
function Home({a,business,setTab}:{a:ReturnType<typeof analyse>;business:Business;setTab:(t:Tab)=>void}){return <><Heading kicker="TUESDAY PERFORMANCE CHECK-IN" title={`Good evening, ${business.name}.`} copy="Here is what your business is telling you this month."/><div className="homeGrid"><Card className="scoreCard"><div className="cardTop"><span>BUSINESS SCORE</span><Badge status={tone(a.score,80,65)}>{a.score>=80?"Strong":a.score>=65?"Needs focus":"At risk"}</Badge></div><div className={`scoreRing ${tone(a.score,80,65)}`} style={{"--score":`${a.score*3.6}deg`} as React.CSSProperties}><div><strong>{a.score}</strong><span>/100</span></div></div><p>{a.score>=80?"Great work. Keep protecting your strongest numbers.":"There is clear money available through pricing, time and retail."}</p></Card><div className="metricStack"><Metric title="MONEY THIS MONTH" value={money.format(a.revenue)} foot={`${money.format(a.afterTax)} after costs and tax reserve`} status={tone(a.operatingProfit,2500,0)}/><Metric title="MONEY EVERY HOUR" value={money.format(a.revenuePerHour)} foot={`Target ${money.format(business.targetHourly)}`} status={tone(a.revenuePerHour,business.targetHourly,business.targetHourly*.8)}/></div><Card className="opportunity"><span>BIGGEST OPPORTUNITY</span><h2>{a.biggest.kind}</h2><strong>{money.format(a.biggest.value)}<small>/year</small></strong><button onClick={()=>setTab(a.biggest.kind==="Pricing"||a.biggest.kind==="Time"?"services":"more")}>See the opportunity →</button></Card></div>
 <div className="kpiGrid"><Kpi label="Operating profit" value={money.format(a.operatingProfit)} sub="after overheads and owner wage" status={tone(a.operatingProfit,3000,0)}/><Kpi label="Gross margin" value={`${Math.round(a.grossProfit/a.revenue*100)}%`} sub="before overheads" status={tone(a.grossProfit/a.revenue*100,70,55)}/><Kpi label="Rebooking" value={`${Math.round(a.rebooking)}%`} sub="team average" status={tone(a.rebooking,70,55)}/><Kpi label="Retail margin" value={`${Math.round(a.retailMargin)}%`} sub={`${money.format(a.retailProfit)} retail profit`} status={tone(a.retailMargin,55,40)}/></div>
 <div className="twoCol"><Card><div className="cardTitle"><div><span>PROFIT BREAKDOWN</span><h2>Where the money goes</h2></div></div><div className="moneyRows"><MoneyRow label="Service revenue" value={a.serviceRevenue}/><MoneyRow label="Retail revenue" value={a.retailRevenue}/><MoneyRow label="Direct product costs" value={-business.services.reduce((s,x)=>s+x.cost*x.clients,0)-business.retail.reduce((s,x)=>s+x.cost*x.units,0)}/><MoneyRow label="Monthly overheads" value={-business.monthlyOverheads}/><MoneyRow label="Owner wage" value={-business.ownerWage}/><MoneyRow total label="Operating profit" value={a.operatingProfit}/></div></Card><Card><div className="cardTitle"><div><span>TODAY'S ACTION</span><h2>Make one change that matters</h2></div></div>{a.serviceResults.slice().sort((x,y)=>Math.max(y.priceOpportunity,y.timeOpportunity)-Math.max(x.priceOpportunity,x.timeOpportunity)).slice(0,3).map(x=><div className="actionRow" key={x.id}><Badge status={x.status}>{x.status==="bad"?"!":x.status==="warn"?"•":"✓"}</Badge><div><b>{x.priceGap?`Raise ${x.name} to ${money.format(x.recommended)}`:`Keep ${x.name} at ${x.minutes} minutes`}</b><span>Worth up to {money.format(Math.max(x.priceOpportunity,x.timeOpportunity))}/year</span></div></div>)}</Card></div></>}
function Metric({title,value,foot,status}:{title:string;value:string;foot:string;status:Status}){return <Card className="metric"><span>{title}</span><strong>{value}</strong><em className={status}>{foot}</em></Card>}
function Kpi({label,value,sub,status}:{label:string;value:string;sub:string;status:Status}){return <Card className={`kpi ${status}`}><span>{label}</span><strong>{value}</strong><small>{sub}</small></Card>}
function MoneyRow({label,value,total=false}:{label:string;value:number;total?:boolean}){return <div className={total?"moneyRow total":"moneyRow"}><span>{label}</span><b className={value<0?"negative":""}>{value<0?"−":""}{money.format(Math.abs(value))}</b></div>}
function Services({business,setBusiness,a}:{business:Business;setBusiness:(b:Business)=>void;a:ReturnType<typeof analyse>}){const update=(id:string,key:keyof Service,value:string)=>setBusiness({...business,services:business.services.map(x=>x.id===id?{...x,[key]:key==="name"?value:Number(value)}:x)});return <><Heading kicker="SERVICE PROFITABILITY" title="Services" copy="See which services pay their way and which need a price or time change."/><div className="serviceList">{a.serviceResults.map(x=><Card className={`serviceCard ${x.status}`} key={x.id}><div className="serviceHead"><input value={x.name} onChange={e=>update(x.id,"name",e.target.value)}/><Badge status={x.status}>{x.status==="good"?"Excellent":x.status==="warn"?"Needs attention":"Underpriced"}</Badge></div><div className="editGrid"><label>Current price<input type="number" value={x.price} onChange={e=>update(x.id,"price",e.target.value)}/></label><label>Time (minutes)<input type="number" value={x.minutes} onChange={e=>update(x.id,"minutes",e.target.value)}/></label><label>Direct cost<input type="number" value={x.cost} onChange={e=>update(x.id,"cost",e.target.value)}/></label><label>Clients / month<input type="number" value={x.clients} onChange={e=>update(x.id,"clients",e.target.value)}/></label></div><div className="serviceNumbers"><div><span>Profit per hour</span><b>{money.format(x.hourly)}</b></div><div><span>Recommended price</span><b>{money.format(x.recommended)}</b></div><div><span>Target time</span><b>{x.targetMinutes} min</b></div><div><span>Potential gain</span><b className="gain">+{money.format(Math.max(x.priceOpportunity,x.timeOpportunity))}/yr</b></div></div><div className="recommend"><b>Best action</b><span>{x.priceGap?`Raise price by ${money.format(x.priceGap)}`:x.minutesToSave?`Save ${x.minutesToSave} minutes`:`Keep and promote this service`}</span></div></Card>)}</div></>}
function Coach({a}:{a:ReturnType<typeof analyse>}){const actions=[...a.serviceResults.map(x=>({title:x.priceGap?`Raise ${x.name} to ${money.format(x.recommended)}`:`Reduce ${x.name} by ${x.minutesToSave} minutes`,value:Math.max(x.priceOpportunity,x.timeOpportunity),status:x.status})),{title:"Improve team rebooking to 70%",value:a.rebookingLoss,status:tone(a.rebooking,70,55) as Status},{title:"Lift retail to 8% of revenue",value:a.retailLoss,status:tone(a.retailRevenue/a.revenue*100,8,5) as Status}].sort((x,y)=>y.value-x.value);return <><Heading kicker="YOUR BUSINESS COACH" title="This month" copy="Do the highest-value actions first. The numbers update as you edit your business."/><Card className="coachScore"><div className={`scoreRing small ${tone(a.score,80,65)}`} style={{"--score":`${a.score*3.6}deg`} as React.CSSProperties}><div><strong>{a.score}</strong><span>/100</span></div></div><div><h2>To reach 90 this month</h2><p>Complete the actions below in order.</p></div></Card><div className="actionList">{actions.slice(0,6).map((x,i)=><Card className="coachAction" key={x.title}><span className="rank">{i+1}</span><div><h3>{x.title}</h3><span>Potential annual gain</span></div><strong>+{money.format(x.value)}</strong><Badge status={x.status}>{x.status}</Badge></Card>)}</div><Card className="totalGain"><span>TOTAL POTENTIAL GAIN</span><strong>+{money.format(a.totalOpportunity)}<small>/year</small></strong></Card></>}
function Goals({business,setBusiness,a}:{business:Business;setBusiness:(b:Business)=>void;a:ReturnType<typeof analyse>}){const annual=a.afterTax*12;const pct=Math.min(100,annual/business.annualGoal*100);return <><Heading kicker="BUILD THE BUSINESS YOU WANT" title="Goals" copy="Set the income target, then see what each booked hour needs to produce."/><Card className="goalHero"><span>What do you want to earn each year?</span><strong>{money.format(business.annualGoal)}</strong><input type="range" min="60000" max="250000" step="5000" value={business.annualGoal} onChange={e=>setBusiness({...business,annualGoal:Number(e.target.value)})}/><div className="progress"><i style={{width:`${pct}%`}}/></div><small>{money.format(annual)} projected from current performance</small></Card><div className="kpiGrid"><Kpi label="Required monthly take-home" value={money.format(business.annualGoal/12)} sub="your annual goal ÷ 12" status="warn"/><Kpi label="Current hourly revenue" value={money.format(a.revenuePerHour)} sub="from service time" status={tone(a.revenuePerHour,business.targetHourly,business.targetHourly*.8)}/><Kpi label="Target hourly revenue" value={money.format(business.targetHourly)} sub="editable target" status="good"/><Kpi label="Goal progress" value={`${Math.round(pct)}%`} sub="current annualised result" status={tone(pct,100,75)}/></div><Card><div className="editGrid goalInputs"><label>Target hourly revenue<input type="number" value={business.targetHourly} onChange={e=>setBusiness({...business,targetHourly:Number(e.target.value)})}/></label><label>Monthly overheads<input type="number" value={business.monthlyOverheads} onChange={e=>setBusiness({...business,monthlyOverheads:Number(e.target.value)})}/></label><label>Owner wage / month<input type="number" value={business.ownerWage} onChange={e=>setBusiness({...business,ownerWage:Number(e.target.value)})}/></label><label>Tax reserve %<input type="number" value={business.taxReserve} onChange={e=>setBusiness({...business,taxReserve:Number(e.target.value)})}/></label></div></Card></>}
function Team({business}:{business:Business}){return <><Heading kicker="SHOP OWNER VIEW" title="Team" copy="Compare hourly performance, rebooking and retail without losing sight of the person."/><div className="teamGrid">{business.team.map(x=>{const hourly=x.revenue/x.hours;const score=Math.round(Math.min(100,hourly/100*45+x.rebooking/100*35+x.retail/18*20));return <Card className="teamCard" key={x.id}><div className="member"><div className="avatar">{x.name[0]}</div><div><h2>{x.name}</h2><Badge status={tone(score,85,70)}>{score}/100</Badge></div></div><div className="memberStats"><div><span>Revenue / hour</span><b>{money.format(hourly)}</b></div><div><span>Rebooking</span><b>{x.rebooking}%</b></div><div><span>Retail attach</span><b>{x.retail}%</b></div><div><span>Monthly revenue</span><b>{money.format(x.revenue)}</b></div></div><div className="recommend"><b>Top opportunity</b><span>{hourly<100?"Improve service mix or timing":x.rebooking<70?"Ask every client to rebook":"Grow retail recommendations"}</span></div></Card>})}</div></>}
function More({a}:{a:ReturnType<typeof analyse>}){const rows=[{label:"Pricing",value:a.pricingLoss,icon:"↗"},{label:"Time",value:a.timeLoss,icon:"◷"},{label:"Retail",value:a.retailLoss,icon:"▣"},{label:"Rebooking",value:a.rebookingLoss,icon:"↻"}];return <><Heading kicker="OPPORTUNITY FINDER" title="Where are you losing money?" copy="These are your biggest annual opportunities based on the numbers entered."/><Card className="opportunityFinder">{rows.map(x=><div className="lossRow" key={x.label}><i>{x.icon}</i><b>{x.label}</b><strong>−{money.format(x.value)}<small>/year</small></strong></div>)}<div className="finderTotal"><span>TOTAL OPPORTUNITY</span><strong>+{money.format(a.totalOpportunity)}<small>/year</small></strong></div></Card><Card className="forecast"><div className="cardTitle"><div><span>GROWTH FORECAST</span><h2>Where you could be in 12 months</h2></div></div><div className="forecastChart"><div className="gridLines"/><svg viewBox="0 0 600 190" preserveAspectRatio="none"><path d="M20 145 C120 125, 180 104, 280 88 S450 48, 580 26"/><circle cx="20" cy="145" r="6"/><circle cx="180" cy="104" r="6"/><circle cx="380" cy="68" r="6"/><circle cx="580" cy="26" r="6"/></svg><div className="axis"><span>Now<br/><b>{a.score}</b></span><span>3m<br/><b>{Math.min(100,a.score+4)}</b></span><span>6m<br/><b>{Math.min(100,a.score+8)}</b></span><span>12m<br/><b>{Math.min(100,a.score+14)}</b></span></div></div><div className="projected"><span>Projected additional profit</span><strong>+{money.format(a.totalOpportunity*.56)}/year</strong></div></Card></>}
